#!/usr/bin/env python3
"""Builds www/emoji/ (a Twemoji SVG subset, CC-BY 4.0) and www/js/emoji-index.js (labels/tags from emojibase-data, MIT).
Usage: npm pack @twemoji/svg@15.0.0 emojibase-data@17.0.0, extract to /tmp/emo/tw and /tmp/emo/eb, then run this."""
import json, os, re, sys
SRC = sys.argv[1] if len(sys.argv) > 1 else '/tmp/emo'
ROOT = os.path.join(os.path.dirname(__file__), '..', 'www')
d = json.load(open(os.path.join(SRC, 'eb/package/en/data.json')))
twdir = os.path.join(SRC, 'tw/package')
tw = set(f[:-4] for f in os.listdir(twdir) if f.endswith('.svg'))
def fname(h):
    h = h.lower()
    if h in tw: return h
    h2 = '-'.join(p for p in h.split('-') if p != 'fe0f')
    return h2 if h2 in tw else None
bad = re.compile(r'\b(man|woman|men|women|person|people|family|couple|kiss|boy|girl|baby|child|adult|older|prince|princess|pregnant|breast|mx|santa|claus|elf|genie|zombie|vampire|merperson|mermaid|merman|fairy|mage|superhero|supervillain|ninja|guard|detective|middle finger|police officer|troll)\b', re.I)
out = os.path.join(ROOT, 'emoji'); os.makedirs(out, exist_ok=True)
rows = []
for e in d:
    g = e.get('group')
    if g is None or g not in (0, 1, 3, 4, 5, 6, 7, 8): continue
    if g == 1 and bad.search(e['label']): continue
    if bad.search(e['label']) and g in (0,): continue
    f = fname(e['hexcode'])
    if not f: continue
    svg = open(os.path.join(twdir, f + '.svg')).read()
    if 'width=' not in svg.split('>')[0]: svg = svg.replace('<svg ', '<svg width="72" height="72" ', 1)
    open(os.path.join(out, f + '.svg'), 'w').write(svg)
    tags = [t for t in (e.get('tags') or []) if t.lower() not in e['label'].lower().split()]
    rows.append([f, e['label'], ' '.join(tags), g])
open(os.path.join(out, 'LICENSE.txt'), 'w').write(
    'Emoji graphics: Twemoji, Copyright 2020 Twitter, Inc and other contributors (https://github.com/jdecked/twemoji).\n'
    'Licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/ . Files are unmodified except for added width/height attributes.\n'
    'Emoji names/keywords: emojibase-data (MIT) https://github.com/milesj/emojibase\n')
js = '/* Generated by tools/build-emoji.py. Emoji: Twemoji (CC-BY 4.0), names/tags: emojibase-data (MIT). [file, label, tags, group] */\n'
js += '(window.VTS = window.VTS || {}).EMOJI_DATA = ' + json.dumps(rows, separators=(',', ':')) + ';\n'
open(os.path.join(ROOT, 'js', 'emoji-index.js'), 'w').write(js)
print(len(rows), 'emoji')
